# Generated by Django 4.2.2 on 2023-06-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='created_at',
        ),
    ]
